
server:
  port: 8083
  servlet:
    context-path: /auth

spring:
  application:
    name: auth
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibermate:
      dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enable: false
  datasource:
    url: jdbc:mysql://localhost:3306/auth?allowPublicKeyRetrieval=true&sslMode=DISABLED&useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: root

security:
  jwt: 
    token: 
      secret-key: chave_microservices
      expire-length: 360000




